version: '3.8'

services:
  meta-analytics-app:
    build: .
    container_name: meta-analytics-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production
    depends_on:
      - meta-analytics-db
      - meta-analytics-redis
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    networks:
      - meta-analytics-network

  meta-analytics-db:
    image: postgres:15-alpine
    container_name: meta-analytics-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=meta_analytics
      - POSTGRES_USER=meta_analytics_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - meta-analytics-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meta-analytics-network

  meta-analytics-redis:
    image: redis:7-alpine
    container_name: meta-analytics-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - meta-analytics-redis-data:/data
    networks:
      - meta-analytics-network

  meta-analytics-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: meta-analytics-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://meta.tryfleur.com/api
    networks:
      - meta-analytics-network

volumes:
  meta-analytics-db-data:
  meta-analytics-redis-data:

networks:
  meta-analytics-network:
    driver: bridge

